import assert from "node:assert/strict";
import test from "node:test";

type MockMapStory = {
  id: number;
  type: string;
  target_id: string;
  language: string;
  content: string;
  is_approved: boolean;
  auto_generated: boolean;
  auto_generation_model: string | null;
  created_at: string;
};

function createMockSupabaseWithStories(initialStories: MockMapStory[]) {
  const db = [...initialStories];

  return {
    from: (table: string) => {
      let queryType = "select";
      let filterLang: string | null = null;
      let filterApproved: boolean | null = null;
      let filterAutoGenerated: boolean | null = null;
      let filterId: number | null = null;
      let filterInIds: number[] | null = null;
      let updatePayload: Partial<MockMapStory> | null = null;

      const chain: any = {
        select: (cols?: string) => {
          queryType = "select";
          return chain;
        },
        update: (payload: Partial<MockMapStory>) => {
          queryType = "update";
          updatePayload = payload;
          return chain;
        },
        delete: () => {
          queryType = "delete";
          return chain;
        },
        eq: (col: string, val: any) => {
          if (col === "language") filterLang = val;
          if (col === "is_approved") filterApproved = val;
          if (col === "auto_generated") filterAutoGenerated = val;
          if (col === "id") filterId = val;
          return chain;
        },
        in: (col: string, vals: any[]) => {
          if (col === "id") filterInIds = vals;
          return chain;
        },
        order: () => chain,
        maybeSingle: async () => {
          const res = await chain._executeQuery();
          return { data: res[0] || null, error: null };
        },
        then: (resolve: any, reject?: any) => {
          return chain._executeQuery().then((data: any) => resolve({ data, error: null }), reject);
        },
        _executeQuery: async () => {
          if (table === "map_targets") {
            return [{ map_type: "sea", target_id: "Bransfield Strait", title_ru: "пролив Брансфилда" }];
          }

          if (table === "map_stories") {
            let matched = db.filter((row) => {
              if (filterLang !== null && row.language !== filterLang) return false;
              if (filterApproved !== null && row.is_approved !== filterApproved) return false;
              if (filterAutoGenerated !== null && row.auto_generated !== filterAutoGenerated) return false;
              if (filterId !== null && row.id !== filterId) return false;
              if (filterInIds !== null && !filterInIds.includes(row.id)) return false;
              return true;
            });

            if (queryType === "update" && updatePayload) {
              matched.forEach((row) => {
                Object.assign(row, updatePayload);
              });
              return matched;
            }

            if (queryType === "delete") {
              const matchedIds = new Set(matched.map((m) => m.id));
              for (let i = db.length - 1; i >= 0; i--) {
                if (matchedIds.has(db[i].id)) db.splice(i, 1);
              }
              return matched;
            }

            return matched;
          }

          return [];
        },
      };
      return chain;
    },
    _getDb: () => db,
  };
}

test("1. Endpoint/Table queries ONLY unapproved AI drafts (language=ru, is_approved=false, auto_generated=true)", async () => {
  const mockStories: MockMapStory[] = [
    {
      id: 1,
      type: "sea",
      target_id: "Bransfield Strait",
      language: "ru",
      content: "История пролива Брансфилда 🌊...",
      is_approved: false,
      auto_generated: true,
      auto_generation_model: "antigravity-ide",
      created_at: new Date().toISOString(),
    },
    {
      id: 2,
      type: "sea",
      target_id: "ApprovedSea",
      language: "ru",
      content: "Утвержденная история...",
      is_approved: true,
      auto_generated: true,
      auto_generation_model: "antigravity-ide",
      created_at: new Date().toISOString(),
    },
    {
      id: 3,
      type: "sea",
      target_id: "ManualStory",
      language: "ru",
      content: "Ручная история...",
      is_approved: false,
      auto_generated: false,
      auto_generation_model: null,
      created_at: new Date().toISOString(),
    },
    {
      id: 4,
      type: "sea",
      target_id: "EnglishStory",
      language: "en",
      content: "English story...",
      is_approved: false,
      auto_generated: true,
      auto_generation_model: "antigravity-ide",
      created_at: new Date().toISOString(),
    },
  ];

  const supabase = createMockSupabaseWithStories(mockStories);

  const { data: drafts } = await supabase
    .from("map_stories")
    .select("*")
    .eq("language", "ru")
    .eq("is_approved", false)
    .eq("auto_generated", true);

  assert.equal(drafts.length, 1);
  assert.equal(drafts[0].id, 1);
  assert.equal(drafts[0].target_id, "Bransfield Strait");
});

test("2. Approve action changes ONLY is_approved = true and preserves original row identity", async () => {
  const initialRow: MockMapStory = {
    id: 1393,
    type: "sea",
    target_id: "Bransfield Strait",
    language: "ru",
    content: "Пролив Брансфилда...",
    is_approved: false,
    auto_generated: true,
    auto_generation_model: "antigravity-ide",
    created_at: "2026-08-06T14:00:00Z",
  };

  const supabase = createMockSupabaseWithStories([initialRow]);

  const { data: updated } = await supabase
    .from("map_stories")
    .update({ is_approved: true })
    .eq("id", 1393)
    .eq("is_approved", false)
    .eq("auto_generated", true);

  assert.equal(updated.length, 1);
  const rowInDb = supabase._getDb().find((r) => r.id === 1393)!;
  assert.equal(rowInDb.is_approved, true);
  assert.equal(rowInDb.target_id, "Bransfield Strait");
  assert.equal(rowInDb.type, "sea");
  assert.equal(rowInDb.content, "Пролив Брансфилда...");
  assert.equal(supabase._getDb().length, 1); // No new row created
});

test("3. Edit action changes ONLY content and preserves draft status", async () => {
  const initialRow: MockMapStory = {
    id: 1394,
    type: "physic",
    target_id: "Island Mafia I.",
    language: "ru",
    content: "Старый текст истории...",
    is_approved: false,
    auto_generated: true,
    auto_generation_model: "antigravity-ide",
    created_at: "2026-08-06T14:00:00Z",
  };

  const supabase = createMockSupabaseWithStories([initialRow]);

  await supabase
    .from("map_stories")
    .update({ content: "Новый отредактированный текст истории..." })
    .eq("id", 1394)
    .eq("is_approved", false)
    .eq("auto_generated", true);

  const rowInDb = supabase._getDb().find((r) => r.id === 1394)!;
  assert.equal(rowInDb.content, "Новый отредактированный текст истории...");
  assert.equal(rowInDb.is_approved, false);
  assert.equal(rowInDb.target_id, "Island Mafia I.");
  assert.equal(rowInDb.type, "physic");
});

test("4. Delete action removes draft row and cannot delete approved story", async () => {
  const draftRow: MockMapStory = {
    id: 1395,
    type: "weather",
    target_id: "Godavari–Krishna mangroves",
    language: "ru",
    content: "Черновик мангров...",
    is_approved: false,
    auto_generated: true,
    auto_generation_model: "antigravity-ide",
    created_at: "2026-08-06T14:00:00Z",
  };

  const approvedRow: MockMapStory = {
    id: 9999,
    type: "river",
    target_id: "Nile",
    language: "ru",
    content: "Утвержденный Нил...",
    is_approved: true,
    auto_generated: true,
    auto_generation_model: "antigravity-ide",
    created_at: "2026-08-06T14:00:00Z",
  };

  const supabase = createMockSupabaseWithStories([draftRow, approvedRow]);

  // Attempt to delete approved story (must fail)
  await supabase
    .from("map_stories")
    .delete()
    .eq("id", 9999)
    .eq("is_approved", false)
    .eq("auto_generated", true);

  assert.equal(supabase._getDb().some((r) => r.id === 9999), true);

  // Delete draft story (must succeed)
  await supabase
    .from("map_stories")
    .delete()
    .eq("id", 1395)
    .eq("is_approved", false)
    .eq("auto_generated", true);

  assert.equal(supabase._getDb().some((r) => r.id === 1395), false);
});

test("5. Batch approval handles partial success gracefully", async () => {
  const rows: MockMapStory[] = [
    {
      id: 1393,
      type: "sea",
      target_id: "Bransfield Strait",
      language: "ru",
      content: "...",
      is_approved: false,
      auto_generated: true,
      auto_generation_model: "antigravity-ide",
      created_at: "2026-08-06T14:00:00Z",
    },
    {
      id: 1394,
      type: "physic",
      target_id: "Island Mafia I.",
      language: "ru",
      content: "...",
      is_approved: false,
      auto_generated: true,
      auto_generation_model: "antigravity-ide",
      created_at: "2026-08-06T14:00:00Z",
    },
    {
      id: 9999, // Already approved
      type: "river",
      target_id: "AlreadyApproved",
      language: "ru",
      content: "...",
      is_approved: true,
      auto_generated: true,
      auto_generation_model: "antigravity-ide",
      created_at: "2026-08-06T14:00:00Z",
    },
  ];

  const supabase = createMockSupabaseWithStories(rows);

  const idsToApprove = [1393, 1394, 9999];
  let approvedCount = 0;
  let failedCount = 0;

  for (const id of idsToApprove) {
    const { data: res } = await supabase
      .from("map_stories")
      .update({ is_approved: true })
      .eq("id", id)
      .eq("is_approved", false)
      .eq("auto_generated", true);

    if (res && res.length > 0) {
      approvedCount += 1;
    } else {
      failedCount += 1;
    }
  }

  assert.equal(approvedCount, 2);
  assert.equal(failedCount, 1);
});
