import type { StopCondition } from "./types";

/**
 * Universal Shared Stop Conditions Registry across all LapLapLa skills.
 */
export const STOP_CONDITIONS_REGISTRY: Record<string, StopCondition> = {
  "STOP-META-01": {
    id: "STOP-META-01",
    category: "METADATA",
    description: "target_id or map_type missing in input object",
    stage: "1. Metadata Lock",
    expectedBehavior: "Discard object (STOP)",
    relatedTest: "TEST-ADV-01",
  },
  "STOP-META-02": {
    id: "STOP-META-02",
    category: "METADATA",
    description: "Object missing in map_targets table (exact SELECT check)",
    stage: "1. Metadata Lock",
    expectedBehavior: "Discard object (STOP)",
    relatedTest: "TEST-ACC-01",
  },
  "STOP-META-03": {
    id: "STOP-META-03",
    category: "METADATA",
    description: "Story map_stories already exists for language",
    stage: "1. Metadata Lock",
    expectedBehavior: "Discard object (STOP)",
    relatedTest: "TEST-ACC-02",
  },
  "STOP-TYPE-01": {
    id: "STOP-TYPE-01",
    category: "TYPE",
    description: "map_type is not in allowable registry list",
    stage: "1. Metadata Lock",
    expectedBehavior: "Discard object (STOP)",
    relatedTest: "TEST-ADV-02",
  },
  "STOP-RESEARCH-01": {
    id: "STOP-RESEARCH-01",
    category: "RESEARCH",
    description: "Facts cannot be confirmed by 2 independent sources",
    stage: "3. Research",
    expectedBehavior: "Discard object (STOP)",
    relatedTest: "TEST-ACC-05",
  },
  "STOP-RESEARCH-02": {
    id: "STOP-RESEARCH-02",
    category: "RESEARCH",
    description: "Entity nature is ambiguous or conflicting",
    stage: "3. Research",
    expectedBehavior: "Discard object (STOP)",
    relatedTest: "TEST-ADV-04",
  },
  "STOP-TYPE-02": {
    id: "STOP-TYPE-02",
    category: "TYPE",
    description: "Text violates Semantic Focus of target map_type",
    stage: "6. Map-Type Review",
    expectedBehavior: "Discard object without type mutation (STOP)",
    relatedTest: "TEST-ADV-03",
  },
  "STOP-FACT-01": {
    id: "STOP-FACT-01",
    category: "FACT",
    description: "Author included unconfirmed fact or hyperbole",
    stage: "7. Fact Check",
    expectedBehavior: "Discard object (STOP)",
    relatedTest: "TEST-ACC-06",
  },
  "STOP-KIDS-01": {
    id: "STOP-KIDS-01",
    category: "KIDS",
    description: "Hook is abstract or CTA is closed yes/no question",
    stage: "8. Kids Editor",
    expectedBehavior: "Discard object (STOP)",
    relatedTest: "TEST-ACC-07",
  },
  "STOP-LANG-01": {
    id: "STOP-LANG-01",
    category: "LANGUAGE",
    description: "Unauthorized Latin token or untranslated fragment in Russian content",
    stage: "8. Kids Editor",
    expectedBehavior: "One retry allowed. Discard object on second failure (STOP)",
    relatedTest: "TEST-ADV-07",
  },
  "STOP-SCHEMA-01": {
    id: "STOP-SCHEMA-01",
    category: "SCHEMA",
    description: "Candidate object fails mandatory database schema fields, types, or non-null constraints",
    stage: "10. Candidate Assembly",
    expectedBehavior: "Discard candidate and block DB write (STOP)",
    relatedTest: "TEST-ADV-08",
  },
  "STOP-DOD-01": {
    id: "STOP-DOD-01",
    category: "DOD",
    description: "Violated one or more canonical DoD criteria",
    stage: "9. Definition of Done",
    expectedBehavior: "Discard object (FAIL)",
    relatedTest: "TEST-ACC-10",
  },
  "STOP-DOCS-01": {
    id: "STOP-DOCS-01",
    category: "DOCS",
    description: "Discrepancy detected between AI-DOCS, code, and DB",
    stage: "Any Stage",
    expectedBehavior: "Halt invocation immediately",
    relatedTest: "TEST-ADV-05",
  },
  "STOP-SAFETY-01": {
    id: "STOP-SAFETY-01",
    category: "SAFETY",
    description: "Attempted unauthorized database mutation or grant breach",
    stage: "Any Stage",
    expectedBehavior: "Refuse and reject call",
    relatedTest: "TEST-ADV-06",
  },
};
